const SCREEN_NAMES = {
    SCREEN_LOGIN: '/login',
    SCREEN_COURSE_REGISTRATION: '/course-registration'
}

const COMMANDS = {
    GET_COURSE: 'GET_COURSE'
}

const INTERNAL_EVENTS = {
    OPEN_WEB_SOCKET: 'OPEN_WEB_SOCKET',
    CLOSE_WEB_SOCKET: 'CLOSE_WEB_SOCKET',
    GET_COURSE: 'GET_COURSE'
}

export { SCREEN_NAMES, COMMANDS, INTERNAL_EVENTS }