delete from COURSE;
delete from STUDENT;

Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'DSA','Data Structure and Algorithms',6,'Edsger Dijkstra','Computer science legend Donald Knuth once said “I don’t understand things unless I try to program them.” We also believe that the best way to learn an algorithm is to program it. However, many excellent books and online courses on algorithms, that excel in introducing algorithmic ideas, have not yet succeeded in teaching you how to implement algorithms, the crucial computer science skill that you have to master at your next job interview.');
Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'OOP','Object Oriented Programming',4,'James Gosling','This Specialization is for aspiring software developers with some programming experience in at least one other programming language (e.g., Python, C, JavaScript, etc.) who want to be able to solve more complex problems through objected-oriented design with Java. In addition to learning Java, you will gain experience with two Java development environments (BlueJ and Eclipse), learn how to program with graphical user interfaces, and learn how to design programs capable of managing large amounts of data.');
Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'Database','Database Systems',5,'Edgar Codd','This specialized program is aimed at computer people who want to enter the field of information systems and learn their different types of requirements, architectures, performance, techniques and tools so you can know when to use business intelligence, data mining, data science, databases , databases in memory or big data in order to have reliable, maintainable and scalable data intensive systems.');
Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'OS','Operating System',3,'Linux Torvard','An operating system acts as an intermediary between the user of a computer and computer hardware. The purpose of an operating system is to provide an environment in which a user can execute programs conveniently and efficiently. An operating system is a software that manages computer hardware. The hardware must provide appropriate mechanisms to ensure the correct operation of the computer system and to prevent user programs from interfering with the proper operation of the system.');
Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'Network','Computer Network',1,'Tim Berners-Lee','In this course, we trace the evolution of networks and identify the key concepts and functions that form the basis for layered architecture. We introduce examples of protocols and services that are familiar to the students, and we explain how these services are supported by networks. Further, we explain fundamental concepts in digital communication, and focus on error control techniques that include parity check, polynomial code, and Internet checksum.');
Insert into COURSE (ID,COURSE_NUMBER,COURSE_NAME,COURSE_LIMIT,TEACHER,DESCRIPTION) values (nextval('COURSE_SEQ'),'CA','Computer Architecture',2,'Alan Turing','We all know what a computer is. It’s that box that sits on your desk, quietly purring away (or rattling if the fan is shot), running your programs and regularly crashing (if you’re not running some variety of Unix). Inside that box is the electronics that runs your software, stores your information, and connects you to the world. It’s all about processing information. Designing a computer, therefore, is about designing a machine that holds and manipulates data.');

Insert into STUDENT (ID,AGE,NAME,PASSWORD,STUDENT_NUMBER) values (nextval('STUDENT_SEQ'),20,'Peter Parker','1','peter');
Insert into STUDENT (ID,AGE,NAME,PASSWORD,STUDENT_NUMBER) values (nextval('STUDENT_SEQ'),22,'John Corner','1','john');
Insert into STUDENT (ID,AGE,NAME,PASSWORD,STUDENT_NUMBER) values (nextval('STUDENT_SEQ'),25,'Harry King','1','harry');

commit;